### PR TITLE
deposit: Harmonizes wording of pub. and img type

### LINKED ISSUE #320: deposit: harmonize wording
phrasing
It would be great to change the heading on these to match phrasing

### PR DESCRIPTION
**Pull request by otron**
* Changed the label for publication type on the upload interface from
"Type of publication" to "Publication Type".
* Resolves #320 

Signed-off-by: otron <oddweb42+gith@gmail.com>

### CODE REVIEW

**Comment by lnielsen** [comment]
Please update the commit message to:

```
deposit: form wording harmonization

* Changes the label for publication type on the upload interface from
  "Type of publication" to "Publication Type". (closes #320)

Signed-off-by: otron <oddweb42+gith@gmail.com>
```

- Lower case letters
- Changed -> Changes
- + closes statement.

**Comment by otron** [comment]
Is there a detailed explanation of the commit message syntax available somewhere?

**Comment by otron** [comment]
Also: Should the pull request be identical to the commit message?

**Comment by lnielsen** [comment]
> Also: Should the pull request be identical to the commit message?

No that's not necessary.

Also see http://invenio-software.org/wiki/Tools/Git/Workflow#R2.Remarksoncommitlogmessages

**Pull request merged**
