### PR TITLE
Updated Readme.rst

### PR DESCRIPTION
**Pull request by jainaman224**
I have visited your page and found that:
1. Readme.rst : Add link to Install.rst 
>>> [Install.rst](https://github.com/zenodo/zenodo/blob/master/INSTALL.rst)

2. Readme.rst : Add gitter badge
>>> Added [Join the chat at https://gitter.im/zenodo/zenodo](https://gitter.im/zenodo/zenodo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

3. Readme.rst : Correct invenio link
>>> [Invenio](http://github.com/inveniosoftware/invenio)

These are some improvement according to me.

### CODE REVIEW

**Comment by satwikkansal** [comment]
@jainaman224 I think you should change the commit shortlog to be more informative like, 
```
Readme.rst : Add link to Install.rst

```
and so on

```
Readme.rst : Correct invenio link
```
as it would make it easy to track the changes later :sweat_smile:

**Comment by krzysztof** [comment]
@jainaman224 Thanks for the changes - looks good to me.

Some minor commit-style nuances:
Can you squash those three commits into one since those are small changes within a single file, and use Zenodo's style of comiting (see an example: https://github.com/zenodo/zenodo/commit/6976cf2e3d37dff29998d3254e57e4dff82ded57)

1. We prepend the commit title with a topic tag, like
``search: fixed and issue with search``, ``docs: updated documentation on foo``, etc.
Sometimes if the changes are big, we use ``global: ``, or if they are specific to an invenio module, for example invenio-accounts, we use ``accounts: ``.

In your case it should be ``docs:``, so something like ``docs: fixed links in README.rst``.

2. Then below the title you have commit body which is a bullet-point list with changes (you can be brief, or in this case even skip it as title is quite self-explanatory). Example of a commit message with a lot of bullet points: https://github.com/zenodo/zenodo/commit/6c84f4f80a064d63e033ccc6572d9d2719fe8fac

3. Finally we usually sign-off the commits, which is an indication from the author to the reviewer/maintainers that the commit/PR is no longer a work in progress and as far as he is concerned it can be merged and is "complete".

You can Sign-off you commits with using a ``--signoff/-s`` flag: ``git commit --signoff``

Thanks again for your contribution :+1:

**Comment by satwikkansal** [comment]
@krzysztof Maybe we should add "Zenodo's style of comiting" guidelines to a doc or wiki somewhere :)

**Comment by krzysztof** [comment]
@satwikkansal Yes, later today we'll push an update to Zenodo docs (zenodo.readthedocs.io), which will address some of the problems with setting up an environment encountered today and contributing to Zenodo.

**Comment by jainaman224** [comment]
@krzysztof I have tried to follow the guidelines. Please have a look.
Thanks for guiding me.

**Pull request merged**
