### PR TITLE
selenium: test_loginpage.py

### PR DESCRIPTION
**Pull request by rajat1994**
a simple selenium test for loginpage.

### CODE REVIEW

**Comment by rajat1994** [comment]
@krzysztof .... could you please review this?

**Comment by krzysztof** [comment]
Hey, last two tests under "Build jobs" on Travis here: https://travis-ci.org/zenodo/zenodo/builds/208634892 are the selenium tests (``E2E=yes``).

They are not passing: https://travis-ci.org/zenodo/zenodo/jobs/208634897 it seems like you're not selecting the correct elements?
``
NoSuchElementException: Message: Unable to locate element: {"method":"id","selector":"email"}
```

**Comment by rajat1994** [comment]
@krzysztof ... in which file i can find the dom elements?

**Comment by krzysztof** [comment]
The login page template: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/theme/templates/zenodo_theme/security/login_user.html (see that it extends and invenio_accounts module template, you'll have to take a look there).

But the easiest you can just check is by looking at the source as you open it in a regular browser.

Did you install selenium locally and tried to run this test (``py.test tests/e2e/``)? Insert a breakpoint inside your test somewhere:
``import ipdb; ipdb.set_trace()``
and try to manually see if you can fetch the elements from the page.

**Comment by lnielsen** [comment]
Closing in favour of https://github.com/inveniosoftware/invenio-app-ils/commit/28d6e6baacf166b619fc0bf1b139334c7c2a5c3c

**Pull request closed without merging**
