### PR TITLE
migration: github integration

### LINKED ISSUE #429: migration: github feature
- [x] Badges #426
- [x] Webhooks #428
- [x] Integrate with account settings
- [x] Migrate module to new code structure.
- Depends on Deposit API

URLs:
- [x] /account/settings/github/
- [x] /account/settings/github/faq
- [x] /account/settings/github/hook/
- [x] /account/settings/github/rejected/
- [x] /account/settings/github/static/
- [x] /account/settings/github/sync/

### PR DESCRIPTION
**Pull request by slint**
* Adds GitHub integration in Zenodo accounts. (closes #429)

* Adds invenio-github to setup.py and requirements.

* Adds configuration for invenio-github.

Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

### CODE REVIEW

**Comment by lnielsen** [comment]
Do you also have a PR for Invenio-GitHub?

**Comment by slint** [comment]
Yup, I will make the PR on Invenio-GitHub in a few moments. I will also update this one for the deposits SIP store issue.

**Comment by krzysztof** [comment]
Things to check:

- [ ] Disconnecting GitHub account from Zenodo should disable all webhooks on repos

**Comment by lnielsen** [comment]
Will you rebase and repush...... I've added latest requirements to allowed failures on travis, so that we can integrate even if they don't pass.

**Pull request merged**
