### PR TITLE
records: show communities in alphabetical order

### LINKED ISSUE #1159: communities: accept/reject communities not listed alphabetically on record detail page
Causes communities to jump around
screen shot 2017-06-03 at 17 07 30

### PR DESCRIPTION
**Pull request by ChiaraBi**
* Close #1159

### CODE REVIEW

**Comment by ChiaraBi** [comment]
Here you can find the feedbacks shown after someone pressed the accept/reject button:
screenshot from 2018-02-09 15-04-32
screenshot from 2018-02-09 15-05-27
screenshot from 2018-02-09 15-05-50
screenshot from 2018-02-09 15-11-04
screenshot from 2018-02-09 15-18-52
screenshot from 2018-02-09 15-19-22

**Comment by ChiaraBi** [comment]
Here you can find the updated feedbacks:
screenshot from 2018-02-28 17-16-55
screenshot from 2018-02-28 17-18-00
screenshot from 2018-02-28 17-18-23

**Comment by krzysztof** [comment]
1. Investigate the missing "Removed" label
2. Refactor JS to just hide/unhide and keep text in template
3. see if we can prevent the community title from rearranging into the buttons column

**Comment by krzysztof** [comment]
1. Investigate the missing "Removed" label
2. Refactor JS to just hide/unhide and keep text in template
3. see if we can prevent the community title from rearranging into the buttons column

**Comment by ChiaraBi** [comment]
The communities' names are now inside a div with a fixed width:
screenshot from 2018-03-01 13-39-01
screenshot from 2018-03-01 13-39-35

**Pull request merged**
