### PR TITLE
Add requirements for local installation

### PR DESCRIPTION
**Pull request by nemobis**
Specify some of the packages required, as a start.

### CODE REVIEW

**Comment by nemobis** [comment]
Still didn't look into why the npm phase fails at:
```
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.20.3-200.fc29.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/node-sass
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
```

**Comment by slint** [comment]
Thanks for taking the time to troubleshoot and document these, we are mostly running Debian-based or MacOS distros, and thus naturally miss some cases/issues. I have to admit though that in general documentation is a bit outdated, and we (i.e. the core Zenodo team) will have to put some aside at some point to get things up to speed with how we develop Zenodo on a day-to-day basis.

I think a better tactic would be to split these throughout the appropriate sections/steps (e.g. `docker` + `docker-compose` before running `docker-compose up ...`, `sudo dnf/yum/apt install lib<xyz>` before `pip install ...`, etc) with explanations for each one of these. 

Suggesting a one-liner tends to be non-educational (*"Why do I need `libraqm-devel`?"*), and will be hard to maintain when e.g. one of these dependencies breaks or stops working (some SSL lbraries have done this in the past in Debian/Ubuntu), or a specific issue occurs.

**Comment by nemobis** [comment]
The second line is simply the list of dependencies to build Pillow, would a comment be enough? Personally I don't want to copy and paste countless commands just to install dependencies.

Ah, node 6... I have node 10. That's definitely worth specifying somewhere prominent. I may try `nvm` or just change approach altogether.

**Comment by slint** [comment]
E.g. for the Pillow dependencies [the official installation docs](https://pillow.readthedocs.io/en/latest/installation.html) provide options/troubleshooting for all sorts of systems (Debian-Linux, Fedora-Linux, MacOS, etc).

For Node, in the ["Media Assets" section](https://zenodo.readthedocs.io/en/latest/installation.html#media-assets) we specify some versions for NodeJS, npm and other JS library dependencies.

**Comment by nemobis** [comment]
Alex Ioannidis, 01/02/19 10:37:
> E.g. for the Pillow dependencies the official installation docs 
> <https://pillow.readthedocs.io/en/latest/installation.html> provide 
> options/troubleshooting for all sorts of systems (Debian-Linux, 
> Fedora-Linux, MacOS, etc).

Sure, that's where I copied the line from.

Personally I just want a one-liner where I can install all the 
dependencies. If it doesn't fit the official docs that's fine, I'll just 
go back to my fork/pull request in the future when I need it.

**Pull request closed without merging**
