### PR TITLE
Bug fix #997

### LINKED ISSUE #997: serializers: BibTex escape special characters
Current BibTex export is not escaping special characters such as ampersands ("&"), causing trouble in applications that use LaTeX. Example record: https://zenodo.org/record/345946/export/hx.

A list/sepcification of these special characters should be found and escaped during serialization using backslashes (eg. `{ Some subject \& another subject }` ). More information can be found in [this SO thread](http://tex.stackexchange.com/questions/7198/how-to-escape-the-ampersand-character-in-bibtex).

### PR DESCRIPTION
**Pull request by vedantrathore**
@slint I've added the test case and the method, I've also validated the bibtex syntax

### CODE REVIEW

**Comment by vedantrathore** [comment]
@slint I dunno why this is failing, all the tests are passing on my pc

**Comment by slint** [comment]
PEP8: https://travis-ci.org/zenodo/zenodo/jobs/215728929#L5340
You should run tests locally before pushing to Travis using the `./run-tests.sh` script on the root of the repository.

I also recommend to check out for any available Python linter integration for your editor such as `pyflake`, `pylinter`, etc. This way you can identify such issues quickly while developing and save time.

**Comment by slint** [comment]
@vedantrathore Travis is still failing because of PEP8 errors. You should be running the tests using the `run-tests.sh` script, at least by calling `py.test --pep8 tests`. Usually error messages are easier to read locally.

**Comment by vedantrathore** [comment]
@slint It's done :)

**Comment by krzysztof** [comment]
Closing since this PR has been integrated as part of big PR cleanup here: https://github.com/zenodo/zenodo/pull/1241

Thanks a lot for the contribution and sorry for the delay :)

**Pull request closed without merging**
