### PR TITLE
deposit: better doi validation in edit form

### PR DESCRIPTION
**Pull request by bouzlibop**
* Adds validation to prevent removal of existing doi. (addresses #231)

Signed-off-by: Adrian Pawel Baran <adrian.pawel.baran@cern.ch>

### CODE REVIEW

**Comment by bouzlibop** [comment]
Failing probably because first it needs [changes in invenio](https://github.com/inveniosoftware/invenio/pull/2994), where I'm adding new argument to `WebDepositField`.

**Comment by bouzlibop** [comment]
Yep, now it's green :white_check_mark:

**Comment by lnielsen** [comment]
Please rebase to latest master and repost. Then I'll integrate it :-) :shipit:

**Comment by bouzlibop** [comment]
Done

**Pull request merged**
