### PR TITLE
WIP: disable removing of DOI on published record while editing

### PR DESCRIPTION
**Pull request by guptavaibhav18197**
Proper validation has been added 
to prevent user from removing DOI while editing a published record. 
ADDRESSING issue #942

### CODE REVIEW

**Comment by guptavaibhav18197** [comment]
@krzysztof Sir
The user was able to leave the doi blank(even for a published record) because 
the metadata dictionary in data  [here](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/loaders/base.py#L54) was not having any key named 'doi', so the validation doi validation function [here](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/fields/doi.py#L78) was NOT being called.
In the PR I made a check - if the record is published and not having 'doi' key  -- then I will add a key,value pair - (doi,'') to the metadata dictionary and made appropriate validation check in the above mentioned validation function.
But the above is failing on [test](https://travis-ci.org/zenodo/zenodo/jobs/217412937#L5045) regarding editing drafts.
Can you please let me know the reason?

**Comment by rajat1994** [comment]
@guptavaibhav18197 .... there are some assertion errors ... 
https://travis-ci.org/zenodo/zenodo/jobs/217412937....check this

**Comment by guptavaibhav18197** [comment]
@rajat1994 
My immediate above comment is regarding that error only[...check it]https://github.com/zenodo/zenodo/pull/1043#issuecomment-292024471)

**Comment by lnielsen** [comment]
@krzysztof @slint Was this problem fixed via the DOI versioning feature? If so, please close.

**Comment by krzysztof** [comment]
It wasn't the problem still persists and this PR addresses it, but unfortunately theere is an issue with unit tests since the DOI check kicks in before the 403 (permission). I am not sure why.

**Pull request closed without merging**
